### ISSUE TITLE
daydream version

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVRClient#1]
Hi, daydream also supports asynchronus timewarp.
¿do you think a daydream version will be possible?

thank you.

**Comment by polygraphene** [comment]
It is possible (https://github.com/polygraphene/ALVR/issues/46#issuecomment-396812846).
The largest issue is absence of Daydream developer.

**Comment by dusan-t** [comment]
I use this to play SteamVR on Android: https://github.com/r57zone/OpenVR-OpenTrack
Freepie IMU sends tracking data from phone to Opentrack and then to SteamVR and then you use Moonlight to stream the image to the phone. It works in SteamVR extended mode only.

**Comment by thoughtfix** [comment]
Subscribing to this issue - Have a Daydream available if you ever need a beta tester.

**Comment by sigmaxipi** [comment]
@penkamaster were you able to get a Daydream version working? Can you email me? I want to chat about some of the technical details.

**Comment by sigmaxipi** [comment]
I have an experimental fork of ALVR for Daydream at https://github.com/sigmaxipi/ALVRClient and an initial release at https://github.com/sigmaxipi/ALVRClient/releases/tag/v2.3.0-daydream

This code is nowhere near ready for general use and the fork breaks the existing GearVR functionality which is why I'm not going to try to merge it into this repo in its existing state.

**Comment by runningman84** [comment]
The daydream app does not seem to work on my axon 7. The app was closed is the error message.

**Comment by gljones2001** [comment]
I HAVE A DAYDREAM!!! I will gladly test this, as i really want to do vivecraft. Tell you how it works soon.

**Comment by gljones2001** [comment]
Nevermind... My graphics is an NVS 5200M. Dosent have NVENC. Dang Nabbit! 😞

**Comment by ShalokShalom** [comment]
Does the current version do work with the Vapor the Google daydream?
