### ISSUE TITLE
ALVR client crashes on startup

### ISSUE THREAD

**Issue by zackmorgs** [polygraphene/ALVRClient#20]
Right now the app just crashes on launch on my moto g5 plus. I am running a strange os though, it's pixel experience 'potter' if you're wondering.

Anyways I've cloned this client you've so graciously put on here. Thanks so much! You freakin rule.

PS Is this even going to work? Current system: windows moto g5 plus -> gear vr (white one from 3 years ago)

PSS i have a leap motion. should I pursue hooking this up?

cheers, ill let you know what I find today if anything. not a big android dev.

---

I apologize for making you read forever, maybe you noticed I posted the already on ALVR non-client repo. Anyways yeah I can't build this thing man I just spent way too long. Would love to do so but yeah not happening if i cant get to compilation. Anyway you could just update the deps on this thing for starters? You made me install a bunch of old stuff. My poor hard drive. I know only a short university class about android dev and its been a while. Still I was able to build a different project or two in the past.

**Comment by xmljson** [comment]
I have got a LG G5 and it crashes on startup.
Is this project only for Samsung phones?
