### ISSUE TITLE
Vive Focus Version？

### ISSUE THREAD

**Issue by xulzee** [polygraphene/ALVRClient#22]
Hi, Vive Focus also supports asynchronus timewarp.
do you think a Vive Focus version will be possible?

thank you.

**Comment by polygraphene** [comment]
That will be technically possible.
But I have no time to develop.
We need a developer of Vive Focus.

**Comment by xulzee** [comment]
Hi polygraphene,
I have a vive foucus and I want to try to develop a client that supports vive foucus. 
I have some questions now I would like to ask. For the client, what is going to be done is to paste the decoded picture to the screen, that is, to render a **still picture** in front of the eyes?
I saw a lot of jitter in front of my eyes.

**Comment by polygraphene** [comment]
Hi
That's great! I appreciate your help.

How do you provide tracking information corresponding to the picture?
Even when you provide the same still pictures for each frames, ATW will adjust rendering position to match latest head position.
So if you move head during rendering, ATW will move the pictures according to the difference of head orientation between before render and after render.
Maybe this is why you get jitter views.

You must provide correct tracking information for each pictures to get smooth head tracking.
If you want to get smooth tracking for still picture, you should provide exactly same tracking information for each frame.

**Comment by polygraphene** [comment]
In ALVR, when we get tracking information from SDK, we put an integer `FrameIndex` to each tracking information. And then put it on map(HashTable). 
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/ovr_context.cpp#L458
And then on rendering on client, fetch saved tracking info according to FrameIndex corresponding to current rendered picture.
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/ovr_context.cpp#L563

You can get current `FrameIndex` by return value of mDecoderThread.clearAvailable.
By providing it to Focus SDK for ATW, you will get smooth head tracking.
https://github.com/polygraphene/ALVRClient/blob/master/app/src/Ovr/java/com/polygraphene/alvr/OvrThread.java#L180

**Comment by SrzGitHub** [comment]
> 嗨polygraphene，
> 我有一个vive foucus，我想尝试开发一个支持vive foucus的客户端。
> 我现在有一些问题我想问一下。对于客户端，要做的是将解码后的图片粘贴到屏幕上，即在眼前呈现**静态图片**？
> 我看到眼前有很多抖动。

嗨你好，  我想问下  适配 VIVE Foucs 需要怎么初始化 WVR_InitRender呢？  因为我发现必须继承于VRActivity 并且，不能使用 GLSrfaceView 或者SurfaceView，

**Comment by Eva02prot** [comment]
Hi polygraphene,
I'm working on rendering stream video source on HTC Focus by ALVR,but there is a problem terribly confuse me. Focus SDK use its own render context which I think in initRender api, but ALVR manage its own render context in eglInit(), when I run the two context in the same thread, It causes unknown errors. is there some way to solve this conflict?
Thank you very much！
