### ISSUE TITLE
Render freezes a short time from starting

### ISSUE THREAD

**Issue by michael554466** [polygraphene/ALVRClient#24]
After about 10 - 120 seconds of connection, the render stops updating on the headset. I then have to restart my samsung s8 on android pie to complete the loop back to it not working after a time. The tracking continues to work flawlessly.

**Comment by polygraphene** [comment]
What version are you using? If you compiled current master branch, I know client has some bugs.
If you installed on Oculus Store, I want to see output of logcat.
