### ISSUE TITLE
Would you accept a PR for a new UI element?

### ISSUE THREAD

**Issue by jorgeazevedo** [polygraphene/ALVRClient#25]
Hi @polygraphene, I'm thinking of building a UI for the ALVR client to allow users to manually input an IP address. The use cases is connecting to your gaming PC remotely over the internet, or in my case a virtual machine in the cloud.

I've been able to get it to connect by patching the client directly using the instructions in [this issue](https://github.com/polygraphene/ALVR/issues/232). I'm getting a latency of around 80ms which is not superb, but is usable. So far I've played around 6 hours of [blade and sorcery](https://store.steampowered.com/app/629730/Blade_and_Sorcery/)

Would you be open to merging a PR like that? Or is this feature just off the table for now?

**Comment by fbesse** [comment]
This would be a great feature, opening up a lot of possibilities for VR on the cloud.

**Comment by Makz89** [comment]
Yes Wonderfull idea!

**Comment by polygraphene** [comment]
I can merge it. Do you have any plan about implementation?
Client uses poor rendering engine, so you may need many works to introduce new UI.

**Comment by jorgeazevedo** [comment]
Yes! Taking oculus as an example, my plan is to leave com.polygraphene.alvr.OvrActivity alone and implement the UI in a new activity. This new activity would be the first thing the user sees, and it's main purpose is launch OvrActivity without an IP (like it works now) or with an IP if the user provided one. What do you think?

Also - the only hardware I currently have easily available is oculus quest. Would you consider merging the feature for quest only, and then expanding from there if it works OK? Or would you not merge until all platforms are supported?

**Comment by polygraphene** [comment]
You shouldn't add activity for new UI. I think Oculus SDK doesn't recommend activity transition in single app.
You must implement it on same activity and fix current 3D rendering process to implement new UI.

Quest rely on same SDK and graphic API which Go/GearVR has. So you don't need to consider the porting to another environment.

**Comment by jorgeazevedo** [comment]
> You shouldn't add activity for new UI. I think Oculus SDK doesn't recommend activity transition in single app.
Oh. Apologies, I'm new to VR development, I'm only really familiar with Android.

> You must implement it on same activity and fix current 3D rendering process to implement new UI.

That's fair, but it's unlikely that I'm going to be able to do that in the time I have available : -( do you see an easier alternative, something that can be worked in isolation? Maybe using the context menu on quest?

**Comment by off99555** [comment]
@jorgeazevedo I noticed a big perceived motion delay with 6DoF when the latency is 80ms (just on my PC, no cloud). So do you notice the same or you don't?
And how do you even have 80ms delay on the cloud if I already have 80ms just for local machine?

**Comment by jorgeazevedo** [comment]
sorry @off99555 I don't mean to be rude, but I want to keep the conversation on this issue exclusively about the development of this new UI, not general support. But to answer your question, I didn't do any tweaking, it was just the performance I got out of the box with my setup. I see the delay but it doesn't bother me.

**Comment by DavisNT** [comment]
Maybe (at least as a temporary solution) the IP address could be set from computer, via some `adb` command line? 
I assume that many users of ALVR already have adb set up on their computers. 

I can imagine 2 technical implementations: 
1. Create a BroadcastReceiver that stores string extra in SharedPreferences file. Read the IP from SharedPreferences on every startup. Set/unset IP by something like `adb shell am broadcast -a com.polygraphene.alvr.SetServerIP --es ip "10.10.10.10"` from the PC. This would easily be extended with proper GUI over time. 
1. Read IP address from a file on device storage on every startup. Set/unset the IP address by manipulating file from PC. This might add some complexity (and possibly need for Android storage permission).

**Comment by DavisNT** [comment]
@polygraphene @jorgeazevedo I have created pull request https://github.com/polygraphene/ALVRClient/pull/35 that allows to set ALVR server IP via ADB (using a service instead of broadcast).

**Comment by jorgeazevedo** [comment]
@DavisNT yes!! you rock : -) I'll try to find time to give it a whirl this week and leave comments in the PR.

Side note, polygraphene seems to be taking a break at the moment. Are you aware of [JackD83's fork](https://github.com/JackD83/ALVRClient)? It's all the rage now, we might have better luck there!

**Comment by DavisNT** [comment]
@jorgeazevedo Thanks! And I have already submitted a this PR to JackD83's fork: https://github.com/JackD83/ALVRClient/pull/1
