### ISSUE TITLE
Why the original texture/color of the GLTF is not displayed in the loading scene ????

### ISSUE THREAD

**Issue by arunkiddo** [polygraphene/ALVRClient#27]

**Comment by polygraphene** [comment]
Need to fix GL calls and shaders.
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/gltf_model.cpp#L84
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/render.cpp#L222

**Comment by arunkiddo** [comment]
Can you elaborate how to fix the GL calls and shaders. @polygraphene

**Comment by polygraphene** [comment]
The shader changes their color by material name on gltf model.
"Plane": Render floor with grid
"Message": Render provided texture to show ALVR version and status message
other: Render gradient color for the sky

Add new if-statement for the sky and put your code to else-statement.
You may need to bind texture and color buffer. Perhaps tiny_gltf library has method to get texture/color.

https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/gltf_model.cpp#L149
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/render.cpp#L275

**Comment by arunkiddo** [comment]
So I did as you told till adding new  if-statement for the sky ,

- Now can I know where are you binding texture and color buffer ?? 

- You have used m_mode 0,1,2 .Can you elaborate each m_mode functions(m_mode0,m_mode1) https://github.com/polygraphene/ALVRClient/blob/60e5f1655f23c3c1e6805e318b317a8a568fb836/app/src/main/cpp/gltf_model.cpp#L150

**Comment by polygraphene** [comment]
Texture for "Message" is set here. Use glBindBuffer to bind color buffer.
https://github.com/polygraphene/ALVRClient/blob/master/app/src/main/cpp/render.cpp#L1068

m_mode corresponds with if-statement(Mode) on the shader.

I think you need to study about opengl. It is difficult to asnwer your all questions about opengl.

**Comment by arunkiddo** [comment]
Yup,Sure After this still I do not get the texture loaded in my gltf.If possible Help me by pointing the code changes.

**Comment by aboutarun** [comment]
@polygraphene Can i know Where Do you load the texture for the loading.gltf ??
Are You loading the color as the texture in the gltf or anything is used ?? @polygraphene

**Comment by polygraphene** [comment]
There is no code to load texture and color buffer. Client ignores them for any gltf models.
You can check following sample from tiny_gltf.
https://github.com/syoyo/tinygltf/
https://github.com/syoyo/tinygltf/blob/master/examples/glview/glview.cc#L408

**Comment by NicFury755** [comment]
@polygraphene  @aboutarun  Whether that is a Lack of Functionality in ALVR Client ??
@polygraphene So We could not add new gltf,If we add also The Texture will not be Loaded ??
@polygraphene Whether I Could Expect this Functionality in ALVR Client.
