### ISSUE TITLE
Latest working source for Oculus Quest

### ISSUE THREAD

**Issue by JackD83** [polygraphene/ALVRClient#30]
Hi
My goal was to fix the ALVR issues with the controllers being the wrong angle on the Oculus Quest. 
I tried to build the latest source from this repo, but its missing classes, others have been refactored, in short: its not building at all for me. 
Whats the latest working source code that supports with the Oculus Quest?

Thanks!

**Comment by zarik5** [comment]
Select the build variant GitubNormalOvrDebug-arm64-v8a

**Comment by JackD83** [comment]
Thank you very much! That worked perfectly. I managed to fix the offset of the controllers, but it seems the tracking is directly transmitting the OVR orientation to the server. The error is better handled on the server side. I'm trying to build that now

**Comment by zarik5** [comment]
If you want to build ALVR server on master head and you can't build CUDA.lib, you should comment [this line](https://github.com/polygraphene/ALVR/blob/master/alvr_server/VideoEncoderNVENC.cpp#L40) and then put a dummy CUDA.lib in `[root]/x64/Release`, you can find the file in the old issues.
