### ISSUE TITLE
samsung SM-G965N not working (arcore client)

### ISSUE THREAD

**Issue by wonjb0303** [polygraphene/ALVRClient#4]
samsung SM-G965N (S9+)
not working

1run app
2 connect gear vr
3 blank screen
4 close app

**Comment by wonjb0303** [comment]
It was solved by a reboot.
but error
Thread Priority Security Exception.

**Comment by polygraphene** [comment]
You need to put osig file on apk before install.
https://github.com/polygraphene/ALVR/wiki/Installation#download-from-github-for-gear-vr-optional

**Comment by wonjb0303** [comment]
Thank you. I appreciate it
