### ISSUE TITLE
Is 4x Multisampling required?

### ISSUE THREAD

**Issue by zbendefy** [polygraphene/ALVRClient#5]
Hi!

I can see, that in render.cpp, ovrFramebuffer_Create() is called with NUM_MULTI_SAMPLES (which is 4). 

I was wondering if 4x multisampling adds anything to the visual quality, I think in the case of texture sampling it might not (but I could be totally wrong on this :) ).

On the other hand it causes 4x as much fragment shaders to be called, that increases the number of texture samples.

**Comment by polygraphene** [comment]
Thank you for reviewing the code!

Multi sample settings is copied by a sample of Oculus Mobile SDK. And I didn't think about that meaning.
I don't have enough knowledge about opengl, but what you said seems right.

I will try NUM_MULTI_SAMPLES = 1.

**Comment by zbendefy** [comment]
I think it would reduce the pixel shaders that have to run by 1/4, and it
would increase battery time and it would lower device temperature hopefully.

polygraphene <notifications@github.com> ezt írta (időpont: 2018. jún. 24.,
Vas 15:55):
