### ISSUE TITLE
Error compiling from sources

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVRClient#7]
Hi,  
I'm having problems compiling from sources. 
Do you have any advice?
(Android studio version or compiling tools)

My objective is create a daydream version.

Thank you.

**Comment by polygraphene** [comment]
My build environment:
Android Studio 3.1.3
build tools 27.0.3 (perhaps)
ndk bundle 17.0.4754217

It's a bit old versions, but latest may also work.

Have you installed ndk?
What's error message?

**Comment by penkamaster** [comment]
Hi, it seems like I have problems with the ndk.
I've reinstaled the ndk and now it works.

Thank you.
